class VCSCommandList:
    def __init__(self):
        self.init = "git init"
        self.add = "git add ."
        self.commit = 'git commit -m "initial commit, autogenerated by start script"'
        self.status = "git status"
