class VCSCommandList:
    def __init__(self):
        self.init = "git init"
        self.add = "git add ."
        self.commit = 'git commit -m "initial commit, autogenerated by start script"'
        self.status = "git status"






"""
Steps to set up git:
git init
copy .gitignore from start_template
git add .
git commit -m "initial commit, autogenerated by start script"
git status
"""
